# Generated by Django 2.1 on 2018-11-03 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolectures',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
