# Generated by Django 2.1 on 2018-11-08 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_videolectures_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursefaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.subcategory')),
            ],
        ),
    ]
