# Generated by Django 2.1 on 2018-11-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_forumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='project.forumcomment'),
        ),
    ]
