# Generated by Django 2.1 on 2018-11-15 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_forumcomment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='syllebus',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
