# Generated by Django 2.0.4 on 2018-12-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_subcategory_syllebus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.subcategory'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='project.forumcomment'),
        ),
    ]
